// Archived PoC helper for this handoff; execute from the workspace root.
import { recipeIdentity } from './ci-median-recipe';
const baselineId=process.argv[2];const sha=process.argv[3];if(!/^[a-f0-9-]{36}$/.test(baselineId??'')||!/^[a-f0-9]{40}$/.test(sha??''))throw Error('Explicit successful baseline UUID and full SHA required');const root='https://cloudbuild.googleapis.com/v1/projects/tastile-dev/locations/asia-northeast1';
const auth=Bun.spawnSync((process.platform === 'win32' ? ['pwsh','-NoProfile','-File','C:/Users/rebui/AppData/Local/Google/Cloud SDK/google-cloud-sdk/bin/gcloud.ps1','auth','print-access-token'] : ['gcloud','auth','print-access-token']));if(auth.exitCode)throw Error('GCP auth failed');const token=auth.stdout.toString().trim();const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};
async function request(path:string,body?:any){const r=await fetch(root+path,{headers,method:body?'POST':'GET',body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error(`Cloud Build HTTP${r.status}`);return await r.json() as any;}
const base=await request('/builds/'+baselineId);if(base.status!=='SUCCESS'){console.log('Baseline '+base.status+'; no replica created');process.exit(2);}if(base.serviceAccount!=='projects/tastile-dev/serviceAccounts/sa-cloud-build-ci@tastile-dev.iam.gserviceaccount.com'||base.source?.storageSource?.object!==`sources/${sha}.tar.gz`||base.availableSecrets||base.secrets?.length||base.steps.some((s:any)=>s.secretEnv?.length||s.status!=='SUCCESS'))throw Error('Baseline trust configuration mismatch');
if(base.timeout!=='1800s'||base.options?.logging!=='CLOUD_LOGGING_ONLY'||base.options?.pool?.name||(base.options?.machineType&&base.options.machineType!=='E2_STANDARD_2'))throw Error('Baseline timeout/logging/pool/machine mismatch before mutation');
const allowed=['name','id','args','entrypoint','env','dir','volumes','waitFor','timeout'];const steps=base.steps.map((s:any)=>Object.fromEntries(allowed.filter(k=>s[k]!==undefined).map(k=>[k,s[k]])));const source=base.source;const ids:any[]=[{sample:1,id:baselineId,origin:'automatic-dispatcher'}];
const recipe=recipeIdentity(steps);const submissionSteps=recipe.submissionSteps;
async function journal(operation:string,evidence:string,result='ok'){const p='docs/journal/dev/'+new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'})+'.jsonl';await Bun.write(p,(await Bun.file(p).exists()?await Bun.file(p).text():'')+JSON.stringify({id:crypto.randomUUID(),ts:new Date().toISOString(),agent:'codex',issue_id:50,execution_generation:Number(process.env.TASTILE_EXECUTION_GENERATION??4),env:'dev',target:'Core CI median PoC',operation,idempotency_key:operation+'-'+sha,result,evidence})+'\n');}
for(let sample=2;sample<=10;sample++){
const sampleTag='sample-'+String(sample).padStart(2,'0');const tags=['tastile-core-ci-poc-g4','source-'+sha,sampleTag];const filter=tags.map(t=>`tags="${t}"`).join(' AND ');const existing=await request('/builds?'+new URLSearchParams({filter,pageSize:'100'}));if(existing.nextPageToken||(existing.builds??[]).length>1)throw Error('Ambiguous replica recovery');
let build=existing.builds?.[0];if(!build){await journal('ci-median-'+sample+'-create-intent',`Exact${sha}/generation${source.storageSource.generation}/samefour-steprecipe; ciSA/defaultE2_STANDARD_2/1800s; no secrets. 9replicas estimatedcompute$1.8 includingoperationalbuffer before sharedpromotional2500min; notahardbillingcap, logs/storage/egress separate. Pricing https://cloud.google.com/build/pricing; no GHstatus/recoverytag mutation.`,'ok');
const operation=await request('/builds',{steps:submissionSteps,source,serviceAccount:base.serviceAccount,timeout:'1800s',options:{logging:'CLOUD_LOGGING_ONLY',machineType:'E2_STANDARD_2'},tags});build=operation.metadata?.build??operation.response;if(!build?.id)throw Error('Create response missing build ID; inspect tags before retry');await journal('ci-median-'+sample+'-create-receipt',`Created${build.id};${sha};sourcegeneration${source.storageSource.generation}; sample${sample}/10.`);}
if(build.source?.storageSource?.generation!==source.storageSource.generation||build.serviceAccount!==base.serviceAccount)throw Error('Recovered replica source/SA mismatch');ids.push({sample,id:build.id,origin:'operator-poc-replica',tags});await Bun.write('.tmp/ci-median-builds.json',JSON.stringify({sha,baselineId,source,stepsDigest:recipe.stepsDigest,resolvedStepsDigest:recipe.stepsDigest,submissionStepsDigest:recipe.submissionStepsDigest,stepsCount:recipe.stepsCount,stepsDigestRelationship:recipe.stepsDigestRelationship,replicaComputeEstimateUsdBeforeCredits:1.8,builds:ids},null,2)+'\n');console.log(JSON.stringify({sample,id:build.id,status:build.status}));
}
