// Generates derived views (D2) and markdown catalogs from the architecture model.
// Output is deterministic so validate.ts can check freshness.
//   bun scripts/architecture/generate.ts          → write architecture/views/*.d2 and architecture/generated/*.md
//   generateAll(model)                            → Map<relative path, content> (used by validate.ts)
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { type Doc, type Model, ROOT, loadModel } from "./model.ts";

const HEADER_D2 = "# GENERATED by scripts/architecture/generate.ts from architecture/model/*.yaml — do not edit.\n";
const HEADER_MD =
  "<!-- GENERATED by scripts/architecture/generate.ts from architecture/model/*.yaml — do not edit. -->\n";

const key = (id: string) => id.replace(/[.-]/g, "_");
// D2 treats `$` inside labels as a substitution start; escape it. Labels are kept single-line.
const q = (s: string) => `"${String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$").replace(/\n/g, " ")}"`;
const cell = (v: unknown) =>
  v === undefined || v === null
    ? ""
    : String(Array.isArray(v) ? v.join(", ") : typeof v === "object" ? JSON.stringify(v) : v)
        .replace(/\|/g, "\\|")
        .replace(/\n/g, " ")
        .trim();

function table(headers: string[], rows: unknown[][]): string {
  const out = [`| ${headers.join(" | ")} |`, `| ${headers.map(() => "---").join(" | ")} |`];
  for (const r of rows) out.push(`| ${r.map(cell).join(" | ")} |`);
  return `${out.join("\n")}\n`;
}

function elementsById(model: Model): Map<string, Doc> {
  return new Map((model.docs.elements.elements as Doc[]).map((e) => [e.id, e]));
}

/** Walk parents until `pred` matches. */
function ancestor(els: Map<string, Doc>, id: string, pred: (e: Doc) => boolean): Doc | undefined {
  let cur = els.get(id);
  while (cur) {
    if (pred(cur)) return cur;
    cur = cur.parent ? els.get(cur.parent) : undefined;
  }
  return undefined;
}

function styleFor(e: Doc): string[] {
  const s: string[] = [];
  if (e.kind === "person") s.push("shape: person");
  if (e.kind === "data_store") s.push("shape: cylinder");
  if (e.kind === "external_system") s.push("style.fill: \"#eeeeee\"");
  if (e.lifecycle === "planned") s.push("style.stroke-dash: 4");
  if (e.lifecycle === "retiring") s.push("style.opacity: 0.45");
  return s;
}

function node(k: string, label: string, styles: string[], indent = ""): string {
  if (styles.length === 0) return `${indent}${k}: ${q(label)}\n`;
  return `${indent}${k}: ${q(label)} {\n${styles.map((s) => `${indent}  ${s}\n`).join("")}${indent}}\n`;
}

function d2Preamble(title: string, direction = "right"): string {
  return `${HEADER_D2}vars: {\n  d2-config: {\n    layout-engine: elk\n  }\n}\ndirection: ${direction}\ntitle: ${q(title)} {\n  near: top-center\n  shape: text\n  style.font-size: 24\n}\n\n`;
}

const isTarget = (x: Doc) => x.lifecycle !== "retiring";
const labelOf = (e: Doc) => (e.technology ? `${e.name}\\n[${e.technology}]` : e.name);

function viewContext(model: Model): string {
  const els = elementsById(model);
  let out = d2Preamble("Tastile — system context (target)");
  const top = (id: string) =>
    ancestor(els, id, (e) => ["person", "software_system", "external_system"].includes(e.kind))?.id;
  const shown = new Set<string>();
  for (const e of els.values()) {
    if (!isTarget(e)) continue;
    if (["person", "software_system", "external_system"].includes(e.kind)) {
      out += node(key(e.id), e.name, styleFor(e));
      shown.add(e.id);
    }
  }
  const edges = new Map<string, string>();
  for (const r of model.docs.relationships.relationships as Doc[]) {
    if (!isTarget(r)) continue;
    const a = top(r.from);
    const b = top(r.to);
    if (!a || !b || a === b || !shown.has(a) || !shown.has(b)) continue;
    const k = `${key(a)} -> ${key(b)}`;
    if (!edges.has(k)) edges.set(k, r.description);
  }
  out += "\n";
  for (const [k, label] of [...edges.entries()].sort()) out += `${k}: ${q(label)}\n`;
  return out;
}

function viewContainers(model: Model): string {
  const els = elementsById(model);
  let out = d2Preamble("Tastile — containers (target)", "down");
  const containerOf = (id: string) =>
    ancestor(els, id, (e) => ["person", "container", "data_store", "external_system"].includes(e.kind));
  const pathOf = (e: Doc) => (e.parent === "sys.tastile" ? `outer.sys_tastile.${key(e.id)}` : `outer.${key(e.id)}`);
  out += "outer: \"\" {\n  grid-rows: 1\n  grid-gap: 40\n";
  out += "  users_and_externals: \"\" {\n    grid-columns: 1\n    grid-gap: 30\n";
  for (const e of els.values()) {
    if (!isTarget(e)) continue;
    if (e.kind === "person" || e.kind === "external_system") out += node(key(e.id), e.name, styleFor(e), "    ");
  }
  out += "  }\n";
  out += "  sys_tastile: \"Tastile\" {\n    style.fill: \"#f4f8ff\"\n";
  for (const e of els.values()) {
    if (!isTarget(e) || e.parent !== "sys.tastile") continue;
    out += node(key(e.id), labelOf(e), styleFor(e), "    ");
  }
  out += "  }\n}\n\n";
  const edges = new Map<string, string>();
  for (const r of model.docs.relationships.relationships as Doc[]) {
    if (!isTarget(r) || r.from.startsWith("repo.") || r.to.startsWith("repo.")) continue;
    const a = containerOf(r.from);
    const b = containerOf(r.to);
    if (!a || !b || a.id === b.id || !isTarget(a) || !isTarget(b)) continue;
    const k = `${pathOf(a)} -> ${pathOf(b)}`;
    const label = r.credential ? r.credential.replace(/^cred\./, "") : r.protocol.split(" ")[0];
    if (!edges.has(k)) edges.set(k, label);
  }
  for (const [k, label] of [...edges.entries()].sort()) out += `${k}: ${q(label)}\n`;
  return out;
}

function viewComponents(model: Model): string {
  const els = elementsById(model);
  let out = d2Preamble("Tastile — components of server-side containers (target)");
  const expanded = ["ctr.edge", "ctr.web", "ctr.core-api", "ctr.core-worker"];
  const pathOf = (id: string): string | undefined => {
    const e = els.get(id);
    if (!e) return undefined;
    if (e.kind === "component" && expanded.includes(e.parent)) return `${key(e.parent)}.${key(e.id)}`;
    const c = ancestor(els, id, (x) => ["person", "container", "data_store", "external_system"].includes(x.kind));
    return c ? key(c.id) : undefined;
  };
  for (const cid of expanded) {
    const c = els.get(cid);
    if (!c) continue;
    out += `${key(cid)}: ${q(labelOf(c))} {\n`;
    for (const e of els.values()) {
      if (e.parent === cid && e.kind === "component" && isTarget(e)) out += node(key(e.id), labelOf(e), styleFor(e), "  ");
    }
    out += "}\n";
  }
  const referenced = new Set<string>();
  const edges = new Map<string, string>();
  for (const r of model.docs.relationships.relationships as Doc[]) {
    if (!isTarget(r) || r.from.startsWith("repo.") || r.to.startsWith("repo.")) continue;
    const a = pathOf(r.from);
    const b = pathOf(r.to);
    if (!a || !b || a === b) continue;
    const touches = [a, b].some((p) => expanded.some((c) => p.startsWith(key(c))));
    if (!touches) continue;
    for (const p of [a, b]) if (!p.includes(".")) referenced.add(p);
    const k = `${a} -> ${b}`;
    if (!edges.has(k)) edges.set(k, r.credential ? r.credential.replace(/^cred\./, "") : r.protocol.split(" ")[0]);
  }
  for (const p of [...referenced].sort()) {
    if (expanded.map(key).includes(p)) continue;
    const e = [...els.values()].find((x) => key(x.id) === p);
    if (e) out += node(p, e.name, styleFor(e));
  }
  out += "\n";
  for (const [k, label] of [...edges.entries()].sort()) out += `${k}: ${q(label)}\n`;
  return out;
}

function viewTrustZones(model: Model): string {
  const els = elementsById(model);
  let out = d2Preamble("Tastile — trust zones and boundary credentials (target)", "down");
  const zoneOf = new Map<string, string>();
  const rendered = new Set<string>();
  out += "zone_stack: \"\" {\n  grid-rows: 1\n  grid-gap: 60\n";
  for (const z of model.docs.security.trust_zones as Doc[]) {
    out += `  ${key(z.id)}: ${q(z.name)} {\n    grid-columns: 1\n    grid-gap: 25\n`;
    for (const m of z.members as string[]) {
      zoneOf.set(m, z.id);
      const e = els.get(m);
      if (!e || e.kind === "component" || !isTarget(e)) {
        if (!e && m.startsWith("repo.")) {
          out += node(key(m), m, ["shape: document"], "      ");
          rendered.add(m);
        }
        continue;
      }
      out += node(key(m), e.name, styleFor(e), "      ");
      rendered.add(m);
    }
    out += "  }\n";
  }
  out += "}\n";
  const containerOf = (id: string) =>
    ancestor(els, id, (e) => e.kind !== "component")?.id ?? (id.startsWith("repo.") ? id : undefined);
  // One edge per (zone pair, from-element, to-element) is kept, but the credential list is aggregated
  // per zone pair so the picture stays readable.
  const pairCreds = new Map<string, Set<string>>();
  const pairNodes = new Map<string, Set<string>>();
  for (const r of model.docs.relationships.relationships as Doc[]) {
    if (!isTarget(r)) continue;
    const a = containerOf(r.from);
    const b = containerOf(r.to);
    if (!a || !b) continue;
    const za = zoneOf.get(a);
    const zb = zoneOf.get(b);
    if (!za || !zb || za === zb || !rendered.has(a) || !rendered.has(b)) continue;
    const k = `zone_stack.${key(za)}.${key(a)} -> zone_stack.${key(zb)}.${key(b)}`;
    if (!pairCreds.has(k)) pairCreds.set(k, new Set());
    pairCreds.get(k)?.add(r.credential ? r.credential.replace(/^cred\./, "") : "public");
    pairNodes.set(k, (pairNodes.get(k) ?? new Set()).add(r.id));
  }
  out += "\n";
  for (const [k, creds] of [...pairCreds.entries()].sort()) out += `${k}: ${q([...creds].sort().join(", "))}\n`;
  return out;
}

function viewDeployment(model: Model, env: string, which: "target" | "current"): string {
  const els = elementsById(model);
  const envDoc = (model.docs.environments.environments as Doc[]).find((e) => e.id === env);
  let out = d2Preamble(`Tastile — ${envDoc?.name ?? env} deployment (${which})`, "down");
  const nodes = (model.docs.deployment.nodes as Doc[]).filter(
    (n) =>
      (n.env === env || n.id.startsWith("node.shared.")) &&
      (which === "target" ? n.lifecycle !== "retiring" : n.lifecycle !== "planned"),
  );
  const providers = model.docs.deployment.providers as Doc[];
  // Unconnected containers are laid out side by side; stack providers vertically for readability.
  out += "provider_stack: \"\" {\n  grid-rows: 1\n  grid-gap: 40\n  style.opacity: 0\n";
  for (const p of providers) {
    const ns = nodes.filter((n) => n.provider === p.id);
    if (ns.length === 0) continue;
    out += `  ${key(p.id)}: ${q(p.name)} {\n    grid-columns: 1\n    grid-gap: 30\n`;
    for (const n of ns) {
      const cost = n.cost_usd_month ? `\n~$${n.cost_usd_month.value}/mo (${n.cost_usd_month.basis})` : "";
      const svc = n.service.length > 30 ? `${n.service.slice(0, 28)}…` : n.service;
      out += `    ${key(n.id)}: ${q(`${svc}${cost}`)} {\n`;
      if (n.lifecycle === "retiring") out += "      style.opacity: 0.6\n";
      for (const h of n.hosts as string[]) {
        const e = els.get(h);
        if (e) out += node(key(h), e.name, styleFor(e).filter((s) => !s.startsWith("style.opacity")), "      ");
      }
      out += "    }\n";
    }
    out += "  }\n";
  }
  out += "}\n\n";
  if (which === "target" && envDoc?.hostnames) {
    out += "hostnames: \"Public hostnames\" {\n  shape: page\n";
    out += `  label: ${q(Object.entries(envDoc.hostnames as Record<string, string>).map(([k, v]) => `${k}: ${v}`).join("\\n"))}\n}\n`;
  }
  return out;
}

function viewContract(model: Model): string {
  let out = d2Preamble("Tastile — API contract distribution");
  const els = elementsById(model);
  const rels = (model.docs.relationships.relationships as Doc[]).filter(
    (r) => r.from.startsWith("repo.") || r.to.startsWith("repo."),
  );
  const ids = new Set<string>();
  for (const r of rels) {
    ids.add(r.from);
    ids.add(r.to);
  }
  for (const id of [...ids].sort()) {
    const e = els.get(id);
    out += node(key(id), e ? e.name : `${id} (openapi.yaml, tagged)`, e ? styleFor(e) : ["shape: document"]);
  }
  out += "\n";
  for (const r of rels) out += `${key(r.from)} -> ${key(r.to)}: ${q(r.description)}${r.lifecycle === "planned" ? " {style.stroke-dash: 4}" : ""}\n`;
  return out;
}

// ------------------------------------------------------------------ markdown catalogs

function mdElements(model: Model): string {
  const rows = (model.docs.elements.elements as Doc[]).map((e) => [
    `\`${e.id}\``,
    e.kind,
    e.name,
    e.parent ?? "",
    e.repository ?? "",
    e.technology ?? "",
    e.lifecycle + (e.retire_by ? ` → ${e.retire_by}` : ""),
    e.description,
  ]);
  return `${HEADER_MD}# Elements\n\n${table(["id", "kind", "name", "parent", "repo", "technology", "lifecycle", "description"], rows)}`;
}

function mdRelationships(model: Model): string {
  const rows = (model.docs.relationships.relationships as Doc[]).map((r) => [
    `\`${r.id}\``,
    r.from,
    r.to,
    r.protocol,
    r.credential ?? "",
    r.data ?? [],
    r.lifecycle,
    r.current ? `current: ${[r.current.credential, r.current.note].filter(Boolean).join(" — ")}` : "",
    r.description,
  ]);
  return `${HEADER_MD}# Relationships\n\n${table(["id", "from", "to", "protocol", "credential", "data", "lifecycle", "current deviation", "description"], rows)}`;
}

function mdRepositories(model: Model): string {
  const rows = (model.docs.repositories.repositories as Doc[]).map((r) => [
    `\`${r.id}\``,
    r.github,
    r.visibility,
    r.role,
    (r.owns as string[]).join(", "),
    r.versioning,
    r.artifact ?? "",
    r.gate ?? "",
  ]);
  return `${HEADER_MD}# Repositories\n\n${table(["id", "github", "visibility", "role", "owns", "versioning", "artifact", "gate"], rows)}`;
}

function mdSot(model: Model): string {
  const fds = model.docs["sot-registry"].fact_domains as Doc[];
  const loc = (l?: Doc) => (l ? `${l.repo}:${l.path}` : "");
  const rows = fds.map((f) => [
    `\`${f.id}\``,
    f.kind,
    f.name,
    loc(f.canonical),
    loc(f.structured),
    (f.derived ?? []).map((d: Doc) => `${d.repo}:${d.path}`).join(", "),
    f.notes ?? "",
  ]);
  return `${HEADER_MD}# SoT registry — where each fact is canonical\n\n${table(["fact domain", "kind", "name", "canonical", "structured", "derived", "notes"], rows)}`;
}

function mdGlossary(model: Model): string {
  const g = model.docs.glossary;
  const defs = (g.terms as Doc[]).filter((t) => t.definition);
  const refs = (g.terms as Doc[]).filter((t) => t.domain_ref);
  let out = `${HEADER_MD}# System / operations glossary\n\n`;
  out += "## Defined here (mechanism layer)\n\n";
  out += table(["term", "definition", "id"], defs.map((t) => [`**${t.term}**`, t.definition, `\`${t.id}\``]));
  out += "\n## Defined by tastile-core (meaning layer) — pointers only\n\n";
  out += table(["term", "canonical definition", "id"], refs.map((t) => [t.term, t.domain_ref, `\`${t.id}\``]));
  out += "\n## Disambiguation rules\n\n";
  out += table(["words", "rule"], (g.disambiguation as Doc[]).map((d) => [d.words, d.rule]));
  out += "\n## Forbidden terms in canonical root prose\n\n";
  out += table(["pattern", "reason", "use instead"], (g.forbidden_terms as Doc[]).map((f) => [`\`${f.pattern}\``, f.reason, f.replacement]));
  return out;
}

function mdEnvironments(model: Model): string {
  const e = model.docs.environments;
  let out = `${HEADER_MD}# Environments\n\n## Isolation rules\n\n`;
  out += table(["id", "rule"], (e.isolation_rules as Doc[]).map((r) => [`\`${r.id}\``, r.rule]));
  out += "\n## Environments\n\n";
  out += table(
    ["id", "purpose", "data", "database", "secrets", "hostnames", "lifecycle", "current"],
    (e.environments as Doc[]).map((x) => [
      `\`${x.id}\``,
      x.purpose,
      x.data,
      x.database,
      x.secrets,
      Object.entries(x.hostnames ?? {}).map(([k, v]) => `${k}=${v}`),
      x.lifecycle + (x.retire_by ? ` → ${x.retire_by}` : ""),
      x.current?.note ?? x.notes ?? "",
    ]),
  );
  return out;
}

export function costSummary(model: Model): { byEnv: Record<string, number>; maxByEnv: Record<string, number>; total: number; totalMax: number; current: number } {
  const byEnv: Record<string, number> = {};
  const maxByEnv: Record<string, number> = {};
  let current = 0;
  for (const n of model.docs.deployment.nodes as Doc[]) {
    const v = Number(n.cost_usd_month?.value ?? 0);
    const mx = Number(n.cost_usd_month?.max ?? v);
    if (n.lifecycle === "retiring") {
      current += v;
      continue;
    }
    byEnv[n.env] = (byEnv[n.env] ?? 0) + v;
    maxByEnv[n.env] = (maxByEnv[n.env] ?? 0) + mx;
  }
  const round = (x: number) => Math.round(x * 100) / 100;
  for (const k of Object.keys(byEnv)) {
    byEnv[k] = round(byEnv[k]);
    maxByEnv[k] = round(maxByEnv[k]);
  }
  const total = round(Object.values(byEnv).reduce((a, b) => a + b, 0));
  const totalMax = round(Object.values(maxByEnv).reduce((a, b) => a + b, 0));
  return { byEnv, maxByEnv, total, totalMax, current: round(current) };
}

function mdDeployment(model: Model): string {
  const d = model.docs.deployment;
  const c = costSummary(model);
  let out = `${HEADER_MD}# Deployment topology\n\n## Cost summary (USD / month, list-price estimate)\n\n`;
  out += table(
    ["scope", "expected", "upper bound"],
    [
      ...Object.keys(c.byEnv)
        .sort()
        .map((k) => [`target ${k}`, c.byEnv[k], c.maxByEnv[k]]),
      ["**target total**", c.total, c.totalMax],
      ["current (retiring nodes, unverified)", c.current, ""],
      ["budget (quality.yaml cost_budget.pre_launch)", model.docs.quality.cost_budget.target.pre_launch, ""],
    ],
  );
  out += "\n## Providers\n\n";
  out += table(["id", "name", "role", "lifecycle"], (d.providers as Doc[]).map((p) => [`\`${p.id}\``, p.name, p.role, p.lifecycle + (p.retire_by ? ` → ${p.retire_by}` : "")]));
  out += "\n## Nodes\n\n";
  out += table(
    ["id", "env", "provider", "service", "hosts", "config", "cost", "lifecycle"],
    (d.nodes as Doc[]).map((n) => [
      `\`${n.id}\``,
      n.env,
      n.provider,
      n.service,
      n.hosts,
      n.config ?? "",
      n.cost_usd_month ? `${n.cost_usd_month.value}${n.cost_usd_month.max !== undefined ? `–${n.cost_usd_month.max}` : ""} (${n.cost_usd_month.basis}) ${n.cost_usd_month.assumption ?? ""}` : "",
      n.lifecycle,
    ]),
  );
  return out;
}

function mdSecurity(model: Model): string {
  const s = model.docs.security;
  let out = `${HEADER_MD}# Trust boundaries\n\n## Trust zones\n\n`;
  out += table(["id", "name", "members", "description"], (s.trust_zones as Doc[]).map((z) => [`\`${z.id}\``, z.name, z.members, z.description]));
  out += "\n## Credentials\n\n";
  out += table(["id", "name", "holder", "verifier", "properties", "lifecycle"], (s.credentials as Doc[]).map((c) => [`\`${c.id}\``, c.name, c.holder, c.verifier, c.properties ?? "", c.lifecycle + (c.retire_by ? ` → ${c.retire_by}` : "")]));
  out += "\n## Data classes\n\n";
  out += table(["id", "name", "description"], (s.data_classes as Doc[]).map((c) => [`\`${c.id}\``, c.name, c.description]));
  out += `\n## Secret handling (${s.secret_handling.store}; ${s.secret_handling.decision})\n\n`;
  out += table(["id", "rule"], (s.secret_handling.rules as Doc[]).map((r) => [`\`${r.id}\``, r.rule]));
  out += "\n## Controls\n\n";
  out += table(["id", "rule"], (s.controls as Doc[]).map((r) => [`\`${r.id}\``, r.rule]));
  return out;
}

function mdData(model: Model): string {
  const d = model.docs.data;
  let out = `${HEADER_MD}# Data\n\nResidency: ${d.residency}\n\n## Stores\n\n`;
  out += table(["id", "element", "engine", "backup", "objectives", "restore drill"], (d.stores as Doc[]).map((s) => [`\`${s.id}\``, s.element ?? "", s.engine, s.backup, s.objectives, s.restore_drill ?? ""]));
  out += "\n## Datasets\n\n";
  out += table(["id", "store", "classes", "owner", "description", "retention"], (d.datasets as Doc[]).map((s) => [`\`${s.id}\``, s.store ?? "(not stored)", s.classes, s.owner_repo, s.description, s.retention]));
  return out;
}

function mdQuality(model: Model): string {
  const qd = model.docs.quality;
  let out = `${HEADER_MD}# Quality\n\n## Quality goals (rank order)\n\n`;
  out += table(["rank", "id", "goal", "rationale"], (qd.quality_goals as Doc[]).map((g) => [g.rank, `\`${g.id}\``, g.name, g.rationale]));
  out += "\n## SLOs (production, rolling 28 days)\n\n";
  out += table(["id", "goal", "SLI", "target", "status", "baseline / note"], (qd.slos as Doc[]).map((s) => [`\`${s.id}\``, s.goal, s.sli, s.target, s.status, [s.baseline, s.note].filter(Boolean).join(" / ")]));
  out += "\n## Engineering KPIs\n\n";
  out += table(["id", "goal", "definition", "target", "baseline"], (qd.engineering_kpis as Doc[]).map((k) => [`\`${k.id}\``, k.goal, k.definition, k.target, k.baseline]));
  const c = costSummary(model);
  out += `\n## Cost budget\n\nTarget pre-launch: **$${qd.cost_budget.target.pre_launch}/month** (${qd.cost_budget.scope}). Current model estimate: **$${c.total}** expected, **$${c.totalMax}** upper bound. Alerts: ${qd.cost_budget.alert}\n`;
  return out;
}

function mdPocs(model: Model): string {
  let out = `${HEADER_MD}# PoCs\n\n`;
  out += table(["id", "title", "status", "decides", "executed", "evidence"], (model.docs.pocs.pocs as Doc[]).map((p) => [`\`${p.id}\``, p.title, p.status, p.decides, p.executed_at ?? "", p.evidence ?? ""]));
  for (const p of model.docs.pocs.pocs as Doc[]) {
    out += `\n## ${p.id} — ${p.title}\n\n- status: **${p.status}**\n- hypothesis: ${p.hypothesis}\n- method: ${p.method}\n\n`;
    out += table(["criterion", "metric", "op", "threshold", "observed", "result", "note"], (p.criteria as Doc[]).map((c) => [c.id, c.metric, `\`${c.op}\``, c.threshold, c.observed ?? "", c.result ?? "", c.note ?? ""]));
    if (p.findings?.length) {
      out += "\nFindings:\n\n";
      out += table(["id", "finding", "action"], (p.findings as Doc[]).map((f) => [`\`${f.id}\``, f.text, f.action]));
    }
  }
  return out;
}

function mdRisks(model: Model): string {
  const r = model.docs.risks;
  let out = `${HEADER_MD}# Risks and open questions\n\n## Risks\n\n`;
  out += table(["id", "title", "L", "I", "status", "evidence", "mitigation"], (r.risks as Doc[]).map((x) => [`\`${x.id}\``, x.title, x.likelihood, x.impact, x.status, x.evidence ?? "", x.mitigation]));
  out += "\n## Open questions\n\n";
  out += table(["id", "owner", "question", "reference"], (r.open_questions as Doc[]).map((x) => [`\`${x.id}\``, x.owner_repo, x.question, x.reference]));
  return out;
}

function mdRoadmap(model: Model): string {
  let out = `${HEADER_MD}# Migration roadmap\n\n`;
  for (const m of model.docs.roadmap.milestones as Doc[]) {
    out += `## ${m.id} — ${m.title}\n\n- status: **${m.status}**${m.authority ? ` · authority: **${m.authority}**` : ""}${m.depends_on ? ` · depends on: ${m.depends_on.join(", ")}` : ""}${m.tracking ? ` · tracking: ${m.tracking.join(", ")}` : ""}\n`;
    if (m.work?.length) out += `- work:\n${m.work.map((w: string) => `  - ${w}`).join("\n")}\n`;
    out += `- exit criteria:\n${m.exit_criteria.map((w: string) => `  - ${w}`).join("\n")}\n\n`;
  }
  return out;
}

function mdAdrs(model: Model): string {
  const rows = model.adrs.map((a) => [`\`${a.id}\``, `[${a.title}](../../${a.path})`, a.status, a.frontMatter?.supersedes ?? "", a.frontMatter?.scope ?? ""]);
  return `${HEADER_MD}# ADR index (root)\n\n${table(["id", "title", "status", "supersedes", "scope"], rows)}`;
}

function mdIndex(): string {
  return `${HEADER_MD}# Generated catalogs\n\nDerived from \`architecture/model/*.yaml\`. Regenerate with \`bun run architecture:generate\`.\n\n${[
    "elements",
    "relationships",
    "repositories",
    "sot-registry",
    "glossary",
    "environments",
    "deployment",
    "security",
    "data",
    "quality",
    "pocs",
    "risks",
    "roadmap",
    "adrs",
  ]
    .map((n) => `- [${n}](./${n}.md)`)
    .join("\n")}\n`;
}

export const VIEW_FILES = [
  "context",
  "containers",
  "components",
  "trust-zones",
  "deployment-production",
  "deployment-staging",
  "deployment-production-current",
  "contract",
] as const;

export function generateAll(model: Model): Map<string, string> {
  const out = new Map<string, string>();
  out.set("architecture/views/context.d2", viewContext(model));
  out.set("architecture/views/containers.d2", viewContainers(model));
  out.set("architecture/views/components.d2", viewComponents(model));
  out.set("architecture/views/trust-zones.d2", viewTrustZones(model));
  out.set("architecture/views/deployment-production.d2", viewDeployment(model, "env.production", "target"));
  out.set("architecture/views/deployment-staging.d2", viewDeployment(model, "env.staging", "target"));
  out.set("architecture/views/deployment-production-current.d2", viewDeployment(model, "env.production", "current"));
  out.set("architecture/views/contract.d2", viewContract(model));
  out.set("architecture/generated/README.md", mdIndex());
  out.set("architecture/generated/elements.md", mdElements(model));
  out.set("architecture/generated/relationships.md", mdRelationships(model));
  out.set("architecture/generated/repositories.md", mdRepositories(model));
  out.set("architecture/generated/sot-registry.md", mdSot(model));
  out.set("architecture/generated/glossary.md", mdGlossary(model));
  out.set("architecture/generated/environments.md", mdEnvironments(model));
  out.set("architecture/generated/deployment.md", mdDeployment(model));
  out.set("architecture/generated/security.md", mdSecurity(model));
  out.set("architecture/generated/data.md", mdData(model));
  out.set("architecture/generated/quality.md", mdQuality(model));
  out.set("architecture/generated/pocs.md", mdPocs(model));
  out.set("architecture/generated/risks.md", mdRisks(model));
  out.set("architecture/generated/roadmap.md", mdRoadmap(model));
  out.set("architecture/generated/adrs.md", mdAdrs(model));
  return out;
}

if (import.meta.main) {
  const model = loadModel();
  const files = generateAll(model);
  for (const [rel, content] of files) {
    const abs = join(ROOT, rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
  }
  console.log(`generated ${files.size} files`);
}
