[CmdletBinding()]
param([switch]$WhatIf,[switch]$Execute,[string]$Agent='release-verifier',[string]$ArtifactRoot='artifacts\recurring-to-source\release',[uri]$ApiUrl,[string]$RunNamespace)
$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path;$evidence=Join-Path $root 'docs\implementation\recurring-to-source\EVIDENCE.md'
if([IO.Path]::IsPathRooted($ArtifactRoot)){throw 'ArtifactRoot must be workspace-relative.'};$artifactDir=[IO.Path]::GetFullPath((Join-Path $root $ArtifactRoot));if(-not $artifactDir.StartsWith($root+[IO.Path]::DirectorySeparatorChar,[StringComparison]::OrdinalIgnoreCase)){throw 'ArtifactRoot must remain under the workspace root.'}
$steps=@(
 [pscustomobject]@{Layer='core';Dir='tastile-core';Exe='cargo';Args=@('fmt','--all','--','--check');Artifact='core-fmt.log'}
 [pscustomobject]@{Layer='core';Dir='tastile-core';Exe='cargo';Args=@('clippy','--workspace','--all-targets','--','-D','warnings');Artifact='core-clippy.log'}
 [pscustomobject]@{Layer='core';Dir='tastile-core';Exe='cargo';Args=@('test','--workspace');Artifact='core-test.log'}
 [pscustomobject]@{Layer='web';Dir='';Exe=(Join-Path $PSScriptRoot 'invoke-web-gate.ps1');Args=@();Artifact='web-gate.log'}
 [pscustomobject]@{Layer='android';Dir='';Exe=(Join-Path $PSScriptRoot 'invoke-android-gate.ps1');Args=@();Artifact='android-gate.log'}
 [pscustomobject]@{Layer='WSLC';Dir='';Exe=(Join-Path $PSScriptRoot 'invoke-wslc-gate.ps1');Args=@();Artifact='wslc-gate.log'} )
if($WhatIf){"live-stack claim: would acquire for '$Agent'.";foreach($s in $steps){"$($s.Layer): $($s.Exe) $($s.Args -join ' ')`nartifact: $(Join-Path $artifactDir $s.Artifact)"};return}
if(-not $Execute){$lease=& (Join-Path $PSScriptRoot 'release-claim.ps1') -Action Acquire -Agent $Agent|ConvertFrom-Json;try{'Release claim acquired. Re-run with -Execute -ApiUrl <existing stack URL> -RunNamespace <name>; no WSLC or device will be started.'}finally{& (Join-Path $PSScriptRoot 'release-claim.ps1') -Action Release -Agent $Agent -LeaseToken $lease.leaseToken};return}
if(-not $ApiUrl -or -not $RunNamespace){throw '-Execute requires -ApiUrl and -RunNamespace for the existing live stack.'};$lease=& (Join-Path $PSScriptRoot 'release-claim.ps1') -Action Acquire -Agent $Agent|ConvertFrom-Json
try{$sha=(git -C $root rev-parse HEAD).Trim();[IO.Directory]::CreateDirectory($artifactDir)|Out-Null;foreach($s in $steps){$path=Join-Path $artifactDir $s.Artifact;$status='PASS';$command="$($s.Exe) $($s.Args -join ' ')";try{if($s.Dir){Push-Location (Join-Path $root $s.Dir);try{& $s.Exe @($s.Args) *>&1|Tee-Object -FilePath $path}finally{Pop-Location}}elseif($s.Layer -eq 'WSLC'){$command="$($s.Exe) -ApiUrl $ApiUrl -RunNamespace $RunNamespace";& $s.Exe -ApiUrl $ApiUrl -RunNamespace $RunNamespace *>&1|Tee-Object -FilePath $path}else{$command="$($s.Exe) -CoreUrl $ApiUrl";& $s.Exe -CoreUrl $ApiUrl *>&1|Tee-Object -FilePath $path};$ok=$?;$code=$LASTEXITCODE;if(-not $ok -or $code -ne 0){throw "Release gate failed: $($s.Artifact) exit $code"}}catch{$status='FAIL';throw}finally{$id='REL-'+[guid]::NewGuid().ToString('N');$utc=[DateTime]::UtcNow.ToString('o');Add-Content -LiteralPath $evidence -Value ("| $id | RELEASE | $($s.Layer) | $status | ``$command`` | $utc | $sha | $Agent | $path |")}}}finally{& (Join-Path $PSScriptRoot 'release-claim.ps1') -Action Release -Agent $Agent -LeaseToken $lease.leaseToken}
